table _Measures
	lineageTag: 191b3da7-3028-41b2-9e46-44a7aeb39913

	measure TotalBudget = ```
			COALESCE(SUM(FactBudgetExecution[AllocatedBudget]), 0)
			
			```
		formatString: 0
		lineageTag: bd90c528-aaaf-475f-9a87-fbc532b6131f

	measure TotalActualSpend = ```
			COALESCE(SUM(FactBudgetExecution[ActualSpend]), 0)
			
			```
		lineageTag: 05e4818d-3cef-4044-9256-8065e56bacd1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BudgetVariance = ```
			[TotalBudget] - [TotalActualSpend]
			
			```
		lineageTag: 0de665a2-5867-46ef-a823-70cbff11253c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BudgetBurnRate_Pct = ```
			
			DIVIDE(
			    [TotalActualSpend], 
			    [TotalBudget], 
			    0
			)
			```
		lineageTag: 07935cea-0091-4194-b849-55e02778debe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition _Measures = m
		mode: import
		source =
				let
				  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Column1"})
				in
				  #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

